language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_a6e237070ec9_key -iv $encrypted_a6e237070ec9_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
script:
- python app/manage.py test
